[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#5E5CE6"
backgroundColor = "#FBFBFD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D1D2C"
font = "sans serif"
borderColor = "#E7E7EF"
